<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

use App\Models\LocationCountrie;

class LocationCountriesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $countries = [
            ['id' => '1','name' => 'Afghanistan','is_visible' => '1'],
            ['id' => '2','name' => 'Albania','is_visible' => '1'],
            ['id' => '3','name' => 'Algeria','is_visible' => '1'],
            ['id' => '4','name' => 'American Samoa','is_visible' => '1'],
            ['id' => '5','name' => 'Andorra','is_visible' => '1'],
            ['id' => '6','name' => 'Angola','is_visible' => '1'],
            ['id' => '7','name' => 'Anguilla','is_visible' => '1'],
            ['id' => '8','name' => 'Antarctica','is_visible' => '1'],
            ['id' => '9','name' => 'Antigua and Barbuda','is_visible' => '1'],
            ['id' => '10','name' => 'Argentina','is_visible' => '1'],
            ['id' => '11','name' => 'Armenia','is_visible' => '1'],
            ['id' => '12','name' => 'Aruba','is_visible' => '1'],
            ['id' => '13','name' => 'Australia','is_visible' => '1'],
            ['id' => '14','name' => 'Austria','is_visible' => '1'],
            ['id' => '15','name' => 'Azerbaijan','is_visible' => '1'],
            ['id' => '16','name' => 'Bahamas','is_visible' => '1'],
            ['id' => '17','name' => 'Bahrain','is_visible' => '1'],
            ['id' => '18','name' => 'Bangladesh','is_visible' => '1'],
            ['id' => '19','name' => 'Barbados','is_visible' => '1'],
            ['id' => '20','name' => 'Belarus','is_visible' => '1'],
            ['id' => '21','name' => 'Belgium','is_visible' => '1'],
            ['id' => '22','name' => 'Belize','is_visible' => '1'],
            ['id' => '23','name' => 'Benin','is_visible' => '1'],
            ['id' => '24','name' => 'Bermuda','is_visible' => '1'],
            ['id' => '25','name' => 'Bhutan','is_visible' => '1'],
            ['id' => '26','name' => 'Bolivia','is_visible' => '1'],
            ['id' => '27','name' => 'Bosnia and Herzegovina','is_visible' => '1'],
            ['id' => '28','name' => 'Botswana','is_visible' => '1'],
            ['id' => '29','name' => 'Bouvet Island','is_visible' => '1'],
            ['id' => '30','name' => 'Brazil','is_visible' => '1'],
            ['id' => '31','name' => 'British Indian Ocean Territory','is_visible' => '1'],
            ['id' => '32','name' => 'Brunei Darussalam','is_visible' => '1'],
            ['id' => '33','name' => 'Bulgaria','is_visible' => '1'],
            ['id' => '34','name' => 'Burkina Faso','is_visible' => '1'],
            ['id' => '35','name' => 'Burundi','is_visible' => '1'],
            ['id' => '36','name' => 'Cambodia','is_visible' => '1'],
            ['id' => '37','name' => 'Cameroon','is_visible' => '1'],
            ['id' => '38','name' => 'Canada','is_visible' => '1'],
            ['id' => '39','name' => 'Cape Verde','is_visible' => '1'],
            ['id' => '40','name' => 'Cayman Islands','is_visible' => '1'],
            ['id' => '41','name' => 'Central African Republic','is_visible' => '1'],
            ['id' => '42','name' => 'Chad','is_visible' => '1'],
            ['id' => '43','name' => 'Chile','is_visible' => '1'],
            ['id' => '44','name' => 'China','is_visible' => '1'],
            ['id' => '45','name' => 'Christmas Island','is_visible' => '1'],
            ['id' => '46','name' => 'Cocos (Keeling) Islands','is_visible' => '1'],
            ['id' => '47','name' => 'Colombia','is_visible' => '1'],
            ['id' => '48','name' => 'Comoros','is_visible' => '1'],
            ['id' => '49','name' => 'Congo','is_visible' => '1'],
            ['id' => '50','name' => 'Cook Islands','is_visible' => '1'],
            ['id' => '51','name' => 'Costa Rica','is_visible' => '1'],
            ['id' => '52','name' => 'Croatia (Hrvatska)','is_visible' => '1'],
            ['id' => '53','name' => 'Cuba','is_visible' => '1'],
            ['id' => '54','name' => 'Cyprus','is_visible' => '1'],
            ['id' => '55','name' => 'Czech Republic','is_visible' => '1'],
            ['id' => '56','name' => 'Denmark','is_visible' => '1'],
            ['id' => '57','name' => 'Djibouti','is_visible' => '1'],
            ['id' => '58','name' => 'Dominica','is_visible' => '1'],
            ['id' => '59','name' => 'Dominican Republic','is_visible' => '1'],
            ['id' => '60','name' => 'East Timor','is_visible' => '1'],
            ['id' => '61','name' => 'Ecuador','is_visible' => '1'],
            ['id' => '62','name' => 'Egypt','is_visible' => '1'],
            ['id' => '63','name' => 'El Salvador','is_visible' => '1'],
            ['id' => '64','name' => 'Equatorial Guinea','is_visible' => '1'],
            ['id' => '65','name' => 'Eritrea','is_visible' => '1'],
            ['id' => '66','name' => 'Estonia','is_visible' => '1'],
            ['id' => '67','name' => 'Ethiopia','is_visible' => '1'],
            ['id' => '68','name' => 'Falkland Islands (Malvinas)','is_visible' => '1'],
            ['id' => '69','name' => 'Faroe Islands','is_visible' => '1'],
            ['id' => '70','name' => 'Fiji','is_visible' => '1'],
            ['id' => '71','name' => 'Finland','is_visible' => '1'],
            ['id' => '72','name' => 'France','is_visible' => '1'],
            ['id' => '73','name' => 'France, Metropolitan','is_visible' => '1'],
            ['id' => '74','name' => 'French Guiana','is_visible' => '1'],
            ['id' => '75','name' => 'French Polynesia','is_visible' => '1'],
            ['id' => '76','name' => 'French Southern Territories','is_visible' => '1'],
            ['id' => '77','name' => 'Gabon','is_visible' => '1'],
            ['id' => '78','name' => 'Gambia','is_visible' => '1'],
            ['id' => '79','name' => 'Georgia','is_visible' => '1'],
            ['id' => '80','name' => 'Germany','is_visible' => '1'],
            ['id' => '81','name' => 'Ghana','is_visible' => '1'],
            ['id' => '82','name' => 'Gibraltar','is_visible' => '1'],
            ['id' => '83','name' => 'Greece','is_visible' => '1'],
            ['id' => '84','name' => 'Greenland','is_visible' => '1'],
            ['id' => '85','name' => 'Grenada','is_visible' => '1'],
            ['id' => '86','name' => 'Guadeloupe','is_visible' => '1'],
            ['id' => '87','name' => 'Guam','is_visible' => '1'],
            ['id' => '88','name' => 'Guatemala','is_visible' => '1'],
            ['id' => '89','name' => 'Guernsey','is_visible' => '1'],
            ['id' => '90','name' => 'Guinea','is_visible' => '1'],
            ['id' => '91','name' => 'Guinea-Bissau','is_visible' => '1'],
            ['id' => '92','name' => 'Guyana','is_visible' => '1'],
            ['id' => '93','name' => 'Haiti','is_visible' => '1'],
            ['id' => '94','name' => 'Heard and Mc Donald Islands','is_visible' => '1'],
            ['id' => '95','name' => 'Honduras','is_visible' => '1'],
            ['id' => '96','name' => 'Hong Kong','is_visible' => '1'],
            ['id' => '97','name' => 'Hungary','is_visible' => '1'],
            ['id' => '98','name' => 'Iceland','is_visible' => '1'],
            ['id' => '99','name' => 'India','is_visible' => '1'],
            ['id' => '100','name' => 'Indonesia','is_visible' => '1'],
            ['id' => '101','name' => 'Iran','is_visible' => '1'],
            ['id' => '102','name' => 'Iraq','is_visible' => '1'],
            ['id' => '103','name' => 'Ireland','is_visible' => '1'],
            ['id' => '104','name' => 'Isle of Man','is_visible' => '1'],
            ['id' => '105','name' => 'Israel','is_visible' => '1'],
            ['id' => '106','name' => 'Italy','is_visible' => '1'],
            ['id' => '107','name' => 'Ivory Coast','is_visible' => '1'],
            ['id' => '108','name' => 'Jamaica','is_visible' => '1'],
            ['id' => '109','name' => 'Japan','is_visible' => '1'],
            ['id' => '110','name' => 'Jersey','is_visible' => '1'],
            ['id' => '111','name' => 'Jordan','is_visible' => '1'],
            ['id' => '112','name' => 'Kazakhstan','is_visible' => '1'],
            ['id' => '113','name' => 'Kenya','is_visible' => '1'],
            ['id' => '114','name' => 'Kiribati','is_visible' => '1'],
            ['id' => '115','name' => 'Kosovo','is_visible' => '1'],
            ['id' => '116','name' => 'Kuwait','is_visible' => '1'],
            ['id' => '117','name' => 'Kyrgyzstan','is_visible' => '1'],
            ['id' => '118','name' => 'Lao','is_visible' => '1'],
            ['id' => '119','name' => 'Latvia','is_visible' => '1'],
            ['id' => '120','name' => 'Lebanon','is_visible' => '1'],
            ['id' => '121','name' => 'Lesotho','is_visible' => '1'],
            ['id' => '122','name' => 'Liberia','is_visible' => '1'],
            ['id' => '123','name' => 'Libyan Arab Jamahiriya','is_visible' => '1'],
            ['id' => '124','name' => 'Liechtenstein','is_visible' => '1'],
            ['id' => '125','name' => 'Lithuania','is_visible' => '1'],
            ['id' => '126','name' => 'Luxembourg','is_visible' => '1'],
            ['id' => '127','name' => 'Macau','is_visible' => '1'],
            ['id' => '128','name' => 'Macedonia','is_visible' => '1'],
            ['id' => '129','name' => 'Madagascar','is_visible' => '1'],
            ['id' => '130','name' => 'Malawi','is_visible' => '1'],
            ['id' => '131','name' => 'Malaysia','is_visible' => '1'],
            ['id' => '132','name' => 'Maldives','is_visible' => '1'],
            ['id' => '133','name' => 'Mali','is_visible' => '1'],
            ['id' => '134','name' => 'Malta','is_visible' => '1'],
            ['id' => '135','name' => 'Marshall Islands','is_visible' => '1'],
            ['id' => '136','name' => 'Martinique','is_visible' => '1'],
            ['id' => '137','name' => 'Mauritania','is_visible' => '1'],
            ['id' => '138','name' => 'Mauritius','is_visible' => '1'],
            ['id' => '139','name' => 'Mayotte','is_visible' => '1'],
            ['id' => '140','name' => 'Mexico','is_visible' => '1'],
            ['id' => '141','name' => 'Micronesia, Federated States of','is_visible' => '1'],
            ['id' => '142','name' => 'Moldova, Republic of','is_visible' => '1'],
            ['id' => '143','name' => 'Monaco','is_visible' => '1'],
            ['id' => '144','name' => 'Mongolia','is_visible' => '1'],
            ['id' => '145','name' => 'Montenegro','is_visible' => '1'],
            ['id' => '146','name' => 'Montserrat','is_visible' => '1'],
            ['id' => '147','name' => 'Morocco','is_visible' => '1'],
            ['id' => '148','name' => 'Mozambique','is_visible' => '1'],
            ['id' => '149','name' => 'Myanmar','is_visible' => '1'],
            ['id' => '150','name' => 'Namibia','is_visible' => '1'],
            ['id' => '151','name' => 'Nauru','is_visible' => '1'],
            ['id' => '152','name' => 'Nepal','is_visible' => '1'],
            ['id' => '153','name' => 'Netherlands','is_visible' => '1'],
            ['id' => '154','name' => 'Netherlands Antilles','is_visible' => '1'],
            ['id' => '155','name' => 'New Caledonia','is_visible' => '1'],
            ['id' => '156','name' => 'New Zealand','is_visible' => '1'],
            ['id' => '157','name' => 'Nicaragua','is_visible' => '1'],
            ['id' => '158','name' => 'Niger','is_visible' => '1'],
            ['id' => '159','name' => 'Nigeria','is_visible' => '1'],
            ['id' => '160','name' => 'Niue','is_visible' => '1'],
            ['id' => '161','name' => 'Norfolk Island','is_visible' => '1'],
            ['id' => '162','name' => 'North Korea','is_visible' => '1'],
            ['id' => '163','name' => 'Northern Mariana Islands','is_visible' => '1'],
            ['id' => '164','name' => 'Norway','is_visible' => '1'],
            ['id' => '165','name' => 'Oman','is_visible' => '1'],
            ['id' => '166','name' => 'Pakistan','is_visible' => '1'],
            ['id' => '167','name' => 'Palau','is_visible' => '1'],
            ['id' => '168','name' => 'Palestine','is_visible' => '1'],
            ['id' => '169','name' => 'Panama','is_visible' => '1'],
            ['id' => '170','name' => 'Papua New Guinea','is_visible' => '1'],
            ['id' => '171','name' => 'Paraguay','is_visible' => '1'],
            ['id' => '172','name' => 'Peru','is_visible' => '1'],
            ['id' => '173','name' => 'Philippines','is_visible' => '1'],
            ['id' => '174','name' => 'Pitcairn','is_visible' => '1'],
            ['id' => '175','name' => 'Poland','is_visible' => '1'],
            ['id' => '176','name' => 'Portugal','is_visible' => '1'],
            ['id' => '177','name' => 'Puerto Rico','is_visible' => '1'],
            ['id' => '178','name' => 'Qatar','is_visible' => '1'],
            ['id' => '179','name' => 'Reunion','is_visible' => '1'],
            ['id' => '180','name' => 'Romania','is_visible' => '1'],
            ['id' => '181','name' => 'Russian Federation','is_visible' => '1'],
            ['id' => '182','name' => 'Rwanda','is_visible' => '1'],
            ['id' => '183','name' => 'Saint Kitts and Nevis','is_visible' => '1'],
            ['id' => '184','name' => 'Saint Lucia','is_visible' => '1'],
            ['id' => '185','name' => 'Saint Vincent and the Grenadines','is_visible' => '1'],
            ['id' => '186','name' => 'Samoa','is_visible' => '1'],
            ['id' => '187','name' => 'San Marino','is_visible' => '1'],
            ['id' => '188','name' => 'Sao Tome and Principe','is_visible' => '1'],
            ['id' => '189','name' => 'Saudi Arabia','is_visible' => '1'],
            ['id' => '190','name' => 'Senegal','is_visible' => '1'],
            ['id' => '191','name' => 'Serbia','is_visible' => '1'],
            ['id' => '192','name' => 'Seychelles','is_visible' => '1'],
            ['id' => '193','name' => 'Sierra Leone','is_visible' => '1'],
            ['id' => '194','name' => 'Singapore','is_visible' => '1'],
            ['id' => '195','name' => 'Slovakia','is_visible' => '1'],
            ['id' => '196','name' => 'Slovenia','is_visible' => '1'],
            ['id' => '197','name' => 'Solomon Islands','is_visible' => '1'],
            ['id' => '198','name' => 'Somalia','is_visible' => '1'],
            ['id' => '199','name' => 'South Africa','is_visible' => '1'],
            ['id' => '200','name' => 'South Georgia South Sandwich Islands','is_visible' => '1'],
            ['id' => '201','name' => 'South Korea','is_visible' => '1'],
            ['id' => '202','name' => 'Spain','is_visible' => '1'],
            ['id' => '203','name' => 'Sri Lanka','is_visible' => '1'],
            ['id' => '204','name' => 'St. Helena','is_visible' => '1'],
            ['id' => '205','name' => 'St. Pierre and Miquelon','is_visible' => '1'],
            ['id' => '206','name' => 'Sudan','is_visible' => '1'],
            ['id' => '207','name' => 'Suriname','is_visible' => '1'],
            ['id' => '208','name' => 'Svalbard and Jan Mayen Islands','is_visible' => '1'],
            ['id' => '209','name' => 'Swaziland','is_visible' => '1'],
            ['id' => '210','name' => 'Sweden','is_visible' => '1'],
            ['id' => '211','name' => 'Switzerland','is_visible' => '1'],
            ['id' => '212','name' => 'Syrian Arab Republic','is_visible' => '1'],
            ['id' => '213','name' => 'Taiwan','is_visible' => '1'],
            ['id' => '214','name' => 'Tajikistan','is_visible' => '1'],
            ['id' => '215','name' => 'Tanzania','is_visible' => '1'],
            ['id' => '216','name' => 'Thailand','is_visible' => '1'],
            ['id' => '217','name' => 'Togo','is_visible' => '1'],
            ['id' => '218','name' => 'Tokelau','is_visible' => '1'],
            ['id' => '219','name' => 'Tonga','is_visible' => '1'],
            ['id' => '220','name' => 'Trinidad and Tobago','is_visible' => '1'],
            ['id' => '221','name' => 'Tunisia','is_visible' => '1'],
            ['id' => '222','name' => 'Turkey','is_visible' => '1'],
            ['id' => '223','name' => 'Turkmenistan','is_visible' => '1'],
            ['id' => '224','name' => 'Turks and Caicos Islands','is_visible' => '1'],
            ['id' => '225','name' => 'Tuvalu','is_visible' => '1'],
            ['id' => '226','name' => 'Uganda','is_visible' => '1'],
            ['id' => '227','name' => 'Ukraine','is_visible' => '1'],
            ['id' => '228','name' => 'United Arab Emirates','is_visible' => '1'],
            ['id' => '229','name' => 'United Kingdom','is_visible' => '1'],
            ['id' => '230','name' => 'United States','is_visible' => '1'],
            ['id' => '231','name' => 'United States minor outlying islands','is_visible' => '1'],
            ['id' => '232','name' => 'Uruguay','is_visible' => '1'],
            ['id' => '233','name' => 'Uzbekistan','is_visible' => '1'],
            ['id' => '234','name' => 'Vanuatu','is_visible' => '1'],
            ['id' => '235','name' => 'Vatican City State','is_visible' => '1'],
            ['id' => '236','name' => 'Venezuela','is_visible' => '1'],
            ['id' => '237','name' => 'Vietnam','is_visible' => '1'],
            ['id' => '238','name' => 'Virgin Islands (British)','is_visible' => '1'],
            ['id' => '239','name' => 'Virgin Islands (U.S.)','is_visible' => '1'],
            ['id' => '240','name' => 'Wallis and Futuna Islands','is_visible' => '1'],
            ['id' => '241','name' => 'Western Sahara','is_visible' => '1'],
            ['id' => '242','name' => 'Yemen','is_visible' => '1'],
            ['id' => '243','name' => 'Zaire','is_visible' => '1'],
            ['id' => '244','name' => 'Zambia','is_visible' => '1'],
            ['id' => '245','name' => 'Zimbabwe','is_visible' => '1']
        ];

        // foreach ($countries as $country) {
        //     LocationCountrie::create($country);
        // }

        LocationCountrie::insert($countries);
    }
}
